#!/bin/bash

clear
#echo Enter your programm name

#read name

#touch $name
#name = main


find . -type f ! -name "*.*" -exec mv {} {}.cpp \;

rm $name
mv float.cpp float
touch makefile
touch test.hpp
touch float.hpp
touch float.cpp

#indo test.hpp
echo '#ifndef TEST_HPP' >> test.hpp
echo '#define TEST_HPP' >> test.hpp
echo '#include<iostream>' >> test.hpp
echo '#include<cassert>' >> test.hpp
echo '#define YELLOW "\033[01;033m"' >> test.hpp
echo '#define GREEN "\033[01;032m"' >> test.hpp
echo '#define RESET "\033[01;0m"' >> test.hpp
echo ' ' >> test.hpp
echo '#include"float.hpp" ' >> test.hpp
echo ' ' >> test.hpp
echo ' ' >> test.hpp
echo 'void test_v1()' >> test.hpp
echo '{' >> test.hpp
echo '	//empty body' >> test.hpp
echo '}' >> test.hpp
echo 'void test_v2()' >> test.hpp
echo '{' >> test.hpp
echo '	//empty body' >> test.hpp
echo '}' >> test.hpp
echo 'void test_v3()' >> test.hpp
echo '{' >> test.hpp
echo '	//empty body' >> test.hpp
echo '}' >> test.hpp
echo ' ' >> test.hpp
echo ' ' >> test.hpp
echo '#endif // TEST_HPP'>> test.hpp

#into main.cpp
echo '#include"test.hpp"' >> main.cpp
echo " " >> main.cpp
echo "int main()" >> main.cpp
echo "{" >> main.cpp
echo '	test_v1();' >> main.cpp
echo '	test_v2();' >> main.cpp
echo '	test_v3();' >> main.cpp
echo '	std::cout << GREEN; ' >> main.cpp
echo '	std::cout <<  "\n\ntake your time"  <<  std::endl;' >> main.cpp
echo '	std::cout << RESET; ' >> main.cpp
echo "	return 0;" >> main.cpp
echo "}" >> main.cpp

#into float.hpp
echo '' >> float.hpp
echo '#ifndef FLOAT_HPP' >> float.hpp
echo '#define FLOAT_HPP' >> float.hpp
echo ' ' >> float.hpp
echo '#endif //FLOAT_HPP' >> float.hpp

#into float.cpp
echo '#include "float.hpp" '>> float.cpp

#into makefile
echo 'SOURCES := float.cpp main.cpp' >> makefile
echo 'OBJECTS := $(patsubst %.cpp,%.o,$(SOURCES))' >> makefile
echo '' >> makefile
echo '' >> makefile
echo 'all: comp run' >> makefile
echo 'comp:$(OBJECTS)' >> makefile
echo '	@clear ' >> makefile
echo '	@g++ $(OBJECTS) -o smd' >> makefile
echo '' >> makefile
echo 'float.o:' >> makefile
echo '	@g++ -c float.cpp -o float.o -std=c++11' >> makefile
echo '' >> makefile
echo 'main.o:' >> makefile
echo '	@g++ -c main.cpp -o main.o -std=c++11' >> makefile
echo '' >> makefile
echo 'float.dep:' >> makefile
echo '	@g++ -c -MM float.cpp -MT "float.dep float.o" -o float.dep  -std=c++11' >> makefile
echo '' >> makefile
echo 'main.dep:' >> makefile
echo '	@g++ -c -MM main.cpp -MT "main.dep main.o" -o main.dep -std=c++11'  >> makefile
echo '-include float.dep main.dep  -std=c++11' >> makefile


echo ' ' >> makefile
echo 'run:' >> makefile 
echo '	@./smd' >> makefile
echo '	@ctags -R .' >> makefile
echo ' '
echo 'clean:' >> makefile
echo '	rm smd *.o *.dep tags' >> makefile
exec make
